language: python
python:
    - "2.7"

install:
    - pip install --extra-index-url https://testpypi.python.org/pypi -r requirements.txt
    - pip install -r test_requirements.txt
    - pip install coveralls

script:
    - python setup.py develop
    - python runtests.py --with-coverage --cover-package=cloudshell

after_success:
    - coveralls
